//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuddyBiller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuddyBiller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User Type..
        /// </summary>
        internal static string frmLogin_Login_Invalid_User_Type_ {
            get {
                return ResourceManager.GetString("frmLogin_Login_Invalid_User_Type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Try Again.
        /// </summary>
        internal static string frmLogin_Login_Login_Failed__Try_Again {
            get {
                return ResourceManager.GetString("frmLogin_Login_Login_Failed__Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in mandatory fields.
        /// </summary>
        internal static string FrmProducts_btnAdd_Click_Fill_in_mandatory_fields {
            get {
                return ResourceManager.GetString("FrmProducts_btnAdd_Click_Fill_in_mandatory_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the product to be deleted.
        /// </summary>
        internal static string frmProducts_btnDelete_Click_Select_the_product_to_be_deleted {
            get {
                return ResourceManager.GetString("frmProducts_btnDelete_Click_Select_the_product_to_be_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Insert New Product Type..
        /// </summary>
        internal static string frmProductTypes_btnUpdate_Click_Failed_to_Insert_New_Product_Type_ {
            get {
                return ResourceManager.GetString("frmProductTypes_btnUpdate_Click_Failed_to_Insert_New_Product_Type_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Product Type Inserted/Updated Successfully..
        /// </summary>
        internal static string frmProductTypes_btnUpdate_Click_New_Product_Type_Inserted_Updated_Successfully_ {
            get {
                return ResourceManager.GetString("frmProductTypes_btnUpdate_Click_New_Product_Type_Inserted_Updated_Successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Types.
        /// </summary>
        internal static string FrmUserDashboard_productTypeToolStripMenuItem_Click_Product_Types {
            get {
                return ResourceManager.GetString("FrmUserDashboard_productTypeToolStripMenuItem_Click_Product_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new user.
        /// </summary>
        internal static string frmUsers_btnAdd_Click_Failed_to_add_new_user {
            get {
                return ResourceManager.GetString("frmUsers_btnAdd_Click_Failed_to_add_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully created..
        /// </summary>
        internal static string frmUsers_btnAdd_Click_User_successfully_created_ {
            get {
                return ResourceManager.GetString("frmUsers_btnAdd_Click_User_successfully_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete user.
        /// </summary>
        internal static string frmUsers_btnDelete_Click_Failed_to_delete_user {
            get {
                return ResourceManager.GetString("frmUsers_btnDelete_Click_Failed_to_delete_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        internal static string frmUsers_btnDelete_Click_User_deleted_successfully {
            get {
                return ResourceManager.GetString("frmUsers_btnDelete_Click_User_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update user.
        /// </summary>
        internal static string frmUsers_btnUpdate_Click_Failed_to_update_user {
            get {
                return ResourceManager.GetString("frmUsers_btnUpdate_Click_Failed_to_update_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully updated.
        /// </summary>
        internal static string frmUsers_btnUpdate_Click_User_successfully_updated {
            get {
                return ResourceManager.GetString("frmUsers_btnUpdate_Click_User_successfully_updated", resourceCulture);
            }
        }
    }
}
