//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Product
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<decimal> Rate { get; set; }
    public Nullable<decimal> Qty { get; set; }
    public Nullable<System.DateTime> Added_Date { get; set; }

    public virtual ProductType ProductType { get; set; }
    public virtual User Added_By { get; set; }
}
